César Urzola - 201717081 \\
Juan Pablo Gómez - 201614596

# Lab 4: Representación de problemas de programación lineal

# Punto 1

## a)

Se tiene que para retornar los dos diccionarios, al menos m-n soluciones serán básicas y el identificar la base a la que pertenecen va a ser el principal reto. Por ello, se consideran todas las posibles soluciones y los casos en que la matriz se define o no de manera completa.

In [ ]:
def SolucionesBasicas(A,b):
  # Diccionario de visualización
  dic={'Solución': [],'Base': []}
  
  rango=np.linalg.matrix_rank(A)
  zcA=np.size(A[1,:])
  A2=A[0:rango,0:rango]
  A3=A.copy();

  # Creacion de espacios de iteración
  z=np.linspace(0,zcA-1,zcA)
  r=np.linspace(0,rango-1,rango)
  
  # Nuevo vector de soluciones de acuerdo a la nueva matriz
  b2=b[:rango]

  #Recorrido en todas las combinaciones posibles de elementos de la nueva matriz
  for i in combinations(z,rango):
    
    # Creacion de la nueva matriz
    for j in r:
      A2[:,int(j)]=A3[:rango,int(i[int(j)])].copy()

    # Caso en el que la nueva matriz no es de rango completo 
    if np.linalg.det(A2)==0:
      dic1=SolucionesBasicas(A2,b2) 
      dic['Solución'].extend(dic1['Solución'])
      dic['Base'].extend(dic1['Base'])  
    # Caso en el que la nueva matriz es de rango completo  
    else:
      k=np.linalg.solve(A2,b2)
      dic['Solución'].append(k)
      dic['Base'].append(A2.copy().transpose()) 
  return dic


## b) y c)

Ahora, se evalúan los factores de entrada cuando la matriz A es y no de rango completo. Al verificar el planteamiento anterior, se obtienen los siguientes resultados.

In [ ]:
import numpy as np
import pandas as pd
from IPython.display import display
from itertools import combinations

# Solución sistema con primera matriz 
A = np.array([[1, 1, 1, 1, 1],[1, 2, 3, 4, 5],[4, 3, 3, 3, 4]])
b = np.array([[1],[2],[3]])

pd.set_option('max_colwidth',75)

sol = SolucionesBasicas(A, b)

df_sol=pd.DataFrame(sol)
print('\n Soluciones básicas (Matriz de rango completo): \n')
display(df_sol)

# Solución sistema con segunda matriz 
A1=np.array([[1,1,1,1,1],[1,2,3,4,5],[2,3,4,5,6]])

sol2 = SolucionesBasicas(A1, b)

df_sol2=pd.DataFrame(sol2)
print('\n Soluciones básicas (Matriz de rango deficiente): \n')
display(df_sol2)

 Soluciones básicas (Matriz de rango completo):

,Solución,Base
0,"[[0.0], [1.0], [-0.0]]","[[1, 1, 4], [1, 2, 3], [1, 3, 3]]"
1,"[[0.0], [1.0], [-0.0]]","[[1, 1, 4], [1, 2, 3], [1, 4, 3]]"
2,"[[0.0], [1.0], [-0.0]]","[[1, 1, 4], [1, 2, 3], [1, 5, 4]]"
3,"[[2.220446049250313e-16], [1.9999999999999991], [-0.9999999999999996]]","[[1, 1, 4], [1, 3, 3], [1, 4, 3]]"
4,"[[0.25], [1.0], [-0.25]]","[[1, 1, 4], [1, 3, 3], [1, 5, 4]]"
5,"[[0.5], [1.0], [-0.5]]","[[1, 1, 4], [1, 4, 3], [1, 5, 4]]"
6,"[[1.0], [-0.0]]","[[1, 2], [1, 3]]"
7,"[[1.0], [-0.0]]","[[1, 2], [1, 4]]"
8,"[[2.0000000000000004], [-1.0000000000000004]]","[[1, 3], [1, 4]]"
9,"[[1.0], [0.0], [-0.0]]","[[1, 2, 3], [1, 3, 3], [1, 5, 4]]"
10,"[[1.0], [0.0], [-0.0]]","[[1, 2, 3], [1, 4, 3], [1, 5, 4]]"
11,"[[2.0], [-0.9999999999999997], [-3.3306690738754706e-16]]","[[1, 3, 3], [1, 4, 3], [1, 5, 4]]"

 Soluciones básicas (Matriz de rango deficiente):

                                        Solución              Base
0                                 [[0.0], [1.0]]  [[1, 1], [1, 2]]
1                                 [[0.5], [0.5]]  [[1, 1], [1, 3]]
2   [[0.6666666666666667], [0.3333333333333333]]  [[1, 1], [1, 4]]
3                               [[0.75], [0.25]]  [[1, 1], [1, 5]]
4                                [[1.0], [-0.0]]  [[1, 2], [1, 3]]
5                                [[1.0], [-0.0]]  [[1, 2], [1, 4]]
6                                [[1.0], [-0.0]]  [[1, 2], [1, 5]]
7  [[2.0000000000000004], [-1.0000000000000004]]  [[1, 3], [1, 4]]
8  [[1.5000000000000002], [-0.5000000000000002]]  [[1, 3], [1, 5]]
9                                [[3.0], [-2.0]]  [[1, 4], [1, 5]]

# Punto 2

# a)

##1. Variables del problema y su representación:
$x_1:$ Número de toneladas de Carbón. \\
$x_2:$ Número de toneladas de Petróleo.  
$x_3:$ Número de toneladas de Gas.

##2. Función de costo:
$$ f(x) = 600x_1 + 550x_2 + 500x_3 $$

La función de costo busca maximizar la energía producida, en función de las toneladas de cada uno de los materiales. 

##3. Restricciones del problema: 
1) $20x_1 + 18x_2 + 15x_3 \leq 60$ \\
2) $15x_1 + 12x_2 + 10x_3 \leq 75$ \\
3) $200x_1 + 220x_2 + 250x_3 \leq 2.000$   
4) $x_1, x_2, x_3 \geq 0$

La restricciones 1,2 hacen referencia a las límitaciones por emisión de gases nocivos para cada uno de los materiales, la primera hace referencia a las emisiones de bióxido de azufre y la segunda a la emisión de particulas suspendidas. La tercera restricción hace referencia al presupuesto diario que maneja la empresa para la compra de los distintos materiales. Y la última restricción indica que las variables deben ser mayores a cero, ya que se refieren a cantidades.

##4. Planteamiento del problema en forma normal y de forma estándar: 

- Forma normal:

$$ \text{max:} \; 600x_1 + 550x_2 + 500x_3 $$ 

$$20x_1 + 18x_2 + 15x_3 \leq 60 \\
15x_1 + 12x_2 + 10x_3 \leq 75 \\
200x_1 + 220x_2 + 250x_3 \leq 2.000$$   

$$x_1,x_2,x_3 \geq 0$$ 

- Forma estándar: 

$$ \text{min:} \; -600x_1 - 550x_2 - 500x_3 $$ 

$$20x_1 + 18x_2 + 15x_3 + y_1 = 60 \\
15x_1 + 12x_2 + 10x_3 + y_2 = 75 \\
200x_1 + 220x_2 + 250x_3 + y_3 = 2.000$$   

$$x_1,x_2,x_3,y_1,y_2,y_3 \geq 0$$

# b)

###   
Se implementó una función que dada una matriz de coeficientes $A$, un vector de constantes $b$ y una función de costo $f$ que corresponden a una problema de optimización en su forma estándar, devuelve un diccionario que contiene las siguientes entradas: 

- Solución: Soluciones básicas del problema. 
- Base: Matriz base con la que se obtuvo la solución del problema.  
- Tipo: Tipo de solución habiendo 2 categorias, *solución básica factible* y *solución básica no factible*. 
- Valor: Valor de la función de costo en la solución básica encontrada.

**Entradas:** 
- $A$: Matriz de coeficientes asociados a las variables de optimización.  
- $b$: Vector de constantes 
- $f$: Función de costo asociada al problema. 

**Salidas:**
- dict: Diccionario conteniendo los items previamente descritos. 

Para poder emplear esta función, se creó otra función llamada negative_check

In [ ]:
def negative_check(L):  
  check = False 
  for i in L: 
    if (i < 0): 
      check = True
      break 
  return check

In [ ]:
import numpy as np

def sol_est_problem(A,b,f): 

  # Se convierten los arreglos de entrada en numpy arrays.  
  A = np.array(A)
  b = np.array(b).T
  f = np.array(f)    

  # Parámetros del sistema lineal
  m,n = np.shape(A)   

  # Parametros de importancia 
  limite = f.shape[0] # Número de variables reales del problema 
  # Diccionario de visualización
  data = {'Solucion':[],'Base':[], 'Tipo':[], 'Valor':[]} 
  # Todas las soluciones básicas
  solutions = SolucionesBasicas(A,b)

  # Caso en que hay una única solución
  if n == m:  
    data['Solucion'] = solutions['Solución']
    data['Base'] = solutions['Base']
    data['Tipo'] = 'Única solución' 
    S = S[0:limite] 
    try:
      value = np.dot(S,f) # Evaluacion de la solucion
    except: 
      value = None
    data['Valor'].append(value)

  # Caso de interés, n_a>m_b donde n_a-m_b = 2.
  elif n >m :  
    data['Base'] = solutions['Base']
    for S in solutions['Solución']:
    # Clasificacion de las soluciones
      try: 
        check = negative_check(S)
      except: 
        check = True

      if check == True:
        value = None 
        data['Valor'].append(value) 
        data['Tipo'].append('Solución básica no factible')
        try:
          S = S[0:limite]
        except: 
          S = None
        data['Solucion'].append(S) 
      else: 
        S = S[0:limite]
        value = np.dot(S,f) # Evaluación de la solución
        data['Valor'].append(value) 
        data['Tipo'].append('Solución básica factible') 
        data['Solucion'].append(S) 

  # Caso donde no hay solución. 
  elif m > n:  
    data['Solucion'] = None
    data['Base'] = np.array(A)
    data['Tipo'] = None
    data['Valor'] = None
  
  return data

In [ ]:
from IPython.display import display, HTML 
import pandas as pd 
import numpy as np


A =[[20,18,15,1,0,0],
    [15,12,10,0,1,0],
    [200,220,250,0,0,1]] 
b = [60,75,2000]  
f = [-600,-550,-500] 

s = sol_est_problem(A,b,f)
p = pd.DataFrame(data=s)
display(p)

,Solucion,Base,Tipo,Valor
0,"[21.00000000000001, -47.50000000000003, 33.000000000000014]","[[20, 15, 200], [18, 12, 220], [15, 10, 250]]",Solución básica no factible,NaN
1,"[-8.333333333333336, 16.666666666666668, -73.33333333333334]","[[20, 15, 200], [18, 12, 220], [1, 0, 0]]",Solución básica no factible,NaN
2,"[-28.5, 35.0, 82.50000000000001]","[[20, 15, 200], [18, 12, 220], [0, 1, 0]]",Solución básica no factible,NaN
3,"[21.0, -20.0, 2200.0]","[[20, 15, 200], [18, 12, 220], [0, 0, 1]]",Solución básica no factible,NaN
4,"[-0.7142857142857156, 8.571428571428573, -54.285714285714285]","[[20, 15, 200], [15, 10, 250], [1, 0, 0]]",Solución básica no factible,NaN
5,"[-7.5, 14.0, 47.5]","[[20, 15, 200], [15, 10, 250], [0, 1, 0]]",Solución básica no factible,NaN
6,"[20.999999999999982, -23.99999999999997, 3799.999999999997]","[[20, 15, 200], [15, 10, 250], [0, 0, 1]]",Solución básica no factible,NaN
7,"[10.0, -140.0, -75.0]","[[20, 15, 200], [1, 0, 0], [0, 1, 0]]",Solución básica no factible,NaN
8,"[5.0, -40.0, 1000.0]","[[20, 15, 200], [1, 0, 0], [0, 0, 1]]",Solución básica no factible,NaN
9,"[3.0, 30.0, 1400.0]","[[20, 15, 200], [0, 1, 0], [0, 0, 1]]",Solución básica factible,-7.183000e+05
10,"[-1.562500000000002, 9.375000000000002, -52.49999999999999]","[[18, 12, 220], [15, 10, 250], [1, 0, 0]]",Solución básica no factible,NaN
11,"[-12.500000000000004, 19.000000000000004, 34.999999999999986]","[[18, 12, 220], [15, 10, 250], [0, 1, 0]]",Solución básica no factible,NaN
12,"[-6.305039478318694e+16, 7.566047373982434e+16, -5.044031582654953e+18]","[[18, 12, 220], [15, 10, 250], [0, 0, 1]]",Solución básica no factible,NaN
13,"[9.090909090909092, -103.63636363636363, -34.09090909090908]","[[18, 12, 220], [1, 0, 0], [0, 1, 0]]",Solución básica no factible,NaN
14,"[6.250000000000001, -52.50000000000001, 624.9999999999998]","[[18, 12, 220], [1, 0, 0], [0, 0, 1]]",Solución básica no factible,NaN
15,"[3.333333333333334, 35.0, 1266.6666666666665]","[[18, 12, 220], [0, 1, 0], [0, 0, 1]]",Solución básica factible,-6.545833e+05
16,"[8.0, -60.0, -5.0]","[[15, 10, 250], [1, 0, 0], [0, 1, 0]]",Solución básica no factible,NaN
17,"[7.5, -52.5, 125.0]","[[15, 10, 250], [1, 0, 0], [0, 0, 1]]",Solución básica no factible,NaN
18,"[4.0, 35.0, 1000.0]","[[15, 10, 250], [0, 1, 0], [0, 0, 1]]",Solución básica factible,-5.216500e+05
19,"[60.0, 75.0, 2000.0]","[[1, 0, 0], [0, 1, 0], [0, 0, 1]]",Solución básica factible,-1.077250e+06

# Literal c)

In [ ]:
from scipy.optimize import linprog # Librería de optimización  
# Matriz A (Coeficientes de las variables en las restricciones)
A_s = np.array([[20,18,15],
              [15,12,10],
              [200,220,250]])   

# Vector b (Constante en las desigualdades de las restricciones)
b_s = np.array([60,75,2000])  
# Vector c (Coeficientes de las variables en la función de optimización)
c_s = np.array([-600,-550,-500] ) # Se cambia el signo porque se desea maximizar.

# Restricciones para que los valores sean positivos
x1_bounds = (0,None) 
x2_bounds = (0,None)
x3_bounds = (0,None)  

# Forma estándar con variables de holgura.
A_c =[[20,18,15,1,0,0],
    [15,12,10,0,1,0],
    [200,220,250,0,0,1]] 
b_c = [60,75,2000]  
f_c = [-600,-550,-500]

In [ ]:
import time   

start1 = time.time()
res_RevSimplex = linprog(c_s, A_ub=A_s, b_ub=b_s.T, bounds=(x1_bounds, x2_bounds, x3_bounds), method="revised simplex") 
end1 = time.time() 
total1 = end1-start1
print('Revised simplex')
print('Tiempo;', total1)
print('Optimal value:', -res_RevSimplex.fun, '\nX:', res_RevSimplex.x)

start3 = time.time()
res_simplex = linprog(c_s, A_ub=A_s, b_ub=b_s.T, bounds=(x1_bounds, x2_bounds, x3_bounds), method="simplex") 
end3 = time.time() 
total3 = end3-start3
print('Simplex')
print('Tiempo:',total3) 
print('Optimal value:', -res_simplex.fun, '\nX:', res_RevSimplex.x)


start4 = time.time()
res_InteriorPoint = linprog(c_s, A_ub=A_s, b_ub=b_s.T, bounds=(x1_bounds, x2_bounds, x3_bounds), method="interior-point") 
end4 = time.time() 
total4 = end4-start4
print('Interior-point')
print('Tiempo;', total4)
print('Optimal value:', -res_InteriorPoint.fun, '\nX:', res_InteriorPoint.x)


start2 = time.time() 
s = sol_est_problem(A_c,b_c,f_c) 
end2 = time.time() 
total2 = end2-start2  
print('Código propio')
print('Tiempo:', total2)

Revised simplex
Tiempo; 0.00887441635131836
Optimal value: 2000.0
X: [0. 0. 4.]
Simplex
Tiempo: 0.002834320068359375
Optimal value: 2000.0
X: [0. 0. 4.]
Interior-point
Tiempo; 0.009869098663330078
Optimal value: 1999.999999995471
X: [2.99286723e-11 8.88531678e-13 4.00000000e+00]
Código propio
Tiempo: 0.0012905597686767578

De acuerdo con los resultados anteriores, las solución recomendada es $x_1=0$ ,$x_2=0$ y $x_3=4$, lo que en el contexto del problema significa que la recomendación para el gerente de la planta es comprar 4 toneladas de combustible gas diariamente. Algunas de las soluciones que se hallaron inicialmente no resultan "factibles" o viables, no cumplen con el presupuesto de la planta, con la restricciones impuestas por la oficina de protección ambiental o lanzan cantidades negativas de combustible, lo que no tiene sentido práctico. Por consiguiente, la mejor solución que cumple con el presupuesto, con las emisiones diarias de bióxido de azufre, la cantidad de partículas suspendidas, arroja cantidades positivas y con las que se obtiene la máxima producción energética es con las 4 toneladas de combustible gas mencionadas. Lo anterior tiene sentido ya que aunque los otros combustibles son mucho más económicos, tienen un mayor impacto ambiental, lo que hace estas opciones inviables.